project:
  type: website

website:
  title: "VVA"
  navbar:
    left:
      - about.qmd
      - sidebar:tutorials
      - sidebar:take-home
      
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
      - icon: house-fill
        href: index.qmd
        text: " "
        
  sidebar:
  - id: tutorials
    title: "Hands-On Exercises"
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
      - href: hands-on/week01.qmd
        text: Week 01
      - href: hands-on/week02.qmd
        text: Week 02
      - href: hands-on/week03.qmd
        text: Week 03
      - href: hands-on/week04.qmd
        text: Week 04

  - id: take-home
    title: "Take-home Exercises"
    style: "docked"
    collapse-level: 2
    contents: 
      - href: take-home/exercise01.qmd
        text: Exercise 01
      
format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true
    comments:
      hypothesis: true

editor: visual
