project:
  type: website

website:
  title: "VVA"
  navbar:
    left:
      - about.qmd
      - sidebar:tutorials
      - sidebar:take-home
      - sidebar:in-class
      
    right:
      - icon: house-fill
        href: index.qmd
        text: " "
      - icon: github
        href: https://github.com/
        aria-label: GitHub
      - icon: house-fill
        href: index.qmd
        text: " "
        
  sidebar:
  - id: tutorials
    title: "Hands-on Exercises"
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
      - href: hands-on/week01.qmd
        text: Week 01
      - href: hands-on/week02.qmd
        text: Week 02
      - href: hands-on/week03.qmd
        text: Week 03
      - href: hands-on/week04.qmd
        text: Week 04
      - href: hands-on/week05.qmd
        text: Week 05
      - href: hands-on/week07.qmd
        text: Week 07
      - href: hands-on/week09.qmd
        text: Week 08
      - href: hands-on/week10.qmd
        text: Week 09

  - id: take-home
    title: "Take-home Exercises"
    style: "docked"
    collapse-level: 2
    contents: 
      - href: take-home/exercise01.qmd
        text: Exercise 01
      - href: take-home/exercise02.qmd
        text: Exercise 02
        
      
  - id: in-class
    title: "In-class Exercises"
    style: "docked"
    collapse-level: 2
    contents: 
      - href: in-class/exercise04.qmd
        text: Exercise 04
      - href: in-class/exercise05.qmd
        text: Exercise 05
      - href: in-class/exercise07.qmd
        text: Exercise 07
      - href: in-class/exercise08.qmd
        text: Exercise 08
      
format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true
    comments:
      hypothesis: true

editor: visual
