project:
  type: website

website:
  title: "VVA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:tutorials
      
  sidebar:
  - id: tutorials
    title: "Hands-On Exercises"
    style: "docked"
    background: light
    collapse-level: 2
    contents: 
      - href: hands-on/week01.qmd
        text: Week 01
      - href: hands-on/week02.qmd
        text: Week 02
      - href: hands-on/week03.qmd
        text: Week 03
      # navigation items
      
format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: true
    comments:
      hypothesis: true

editor: visual
