---
title: "Week 05's In Class Exercise - Visual Analytics For Building Better Explanatory Models"
format: html
author: Vivian Chew
sidebar: false
date: 02/15/2025 #mm/dd/yyyy
date-format: long
date-modified: last-modified
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

## Getting Started

```{r}
pacman::p_load(tidyverse, 
               readxl, 
               SmartEDA, 
               easystats,
               performance,
               ggstatsplot,
               gtsummary # summarize model results to create table
               )
# R base stats is clumsy and untidy LOL
```

```{r}
car_resale <- read_xls("data/ToyotaCorolla.xls", "data")
```

## Using `SmartEDA` to Explore the Data

```{r}
# Overview of the data - Type = 1
summary1 <- car_resale %>%
  ExpData(type = 1)
```

```{r}
# Structure of the data - Type = 2
summary2 <- car_resale %>%
  ExpData(type = 2)
```

```{r}
cols <- c("Mfg_Month", "HP_Bin", "CC_bin", "Doors", "Gears",
          "Cylinders", "Fuel_Type", "Color", "Met_Color",
          "Automatic", "Mfr_Guarantee", "BOVAG_Guarantee",
          "ABS", "Airbag_1", "Airbag_2", "Airco", "Automatic_airco",
          "Boardcomputer", "CD_Player", "Central_Lock",
          "Powered_Windows", "Power_Steering", "Radio", "Mistlamps",
          "Sport_Model", "Backseat_Divider", "Metallic_Rim",
          "Radio_cassette", "Tow_Bar")
car_resale <- car_resale %>% 
  mutate(Id = as.character(Id)) %>%
  mutate_each_(funs(factor(.)), cols)
```

### Looking at the numerical variables

```{r}
car_resale %>%
  ExpNumViz(target=NULL,
            nlim=10,
            Page=c(2,2))
```

```{r}
car_resale %>%
  ExpNumViz(target = "Price",
            nlim = 10,
            Page = c(2,2)  # Figure layout per page
            )
```

### Looking at the categorical variables

```{r}
#| fig-width: 12
#| fig-height: 10
car_resale %>%
  ExpCatViz(target = NULL,
            clim = 10,
            col = "skyblue",
            margin = 2,
            Page = c(4,4), 
            sample = 16
            )
```

## Using `performance` For Model Statistics

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + Weight + Guarantee_Period,
            data = car_resale)
model
```

```{r}
check_collinearity(model)
```

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```

```{r}
model1 <- lm(Price ~ Age_08_04 + KM + Weight + Guarantee_Period,
            data = car_resale)
check_normality(model1)
```

```{r}
summary(model1)
```

## Using `gtsummary` For Model Statistics in Tabular Form

```{r}
# gtsummary - organise the regression summary into a data table
tbl_regression(model, intercept = TRUE)
```

```{r}
# Include additional statistical measures
tbl_regression(model1,
               intercept = TRUE) %>%
  add_glance_source_note(
    label = list(sigma = "\U03C3"),
    include = c(r.squared, adj.r.squared,
                AIC, statistic,
                p.value, sigma)
  )
```

```{r}
p_model1 <- parameters(model1)
p_model1
```
```{r}
plot(parameters(model1))
```


```{r}
ggcoefstats(model1)
```

